### ISSUE TITLE
how to handle dependency cycles between "foo" and "foo-macros"?

### ISSUE THREAD

**Issue by tamird** [Byron/cargo-smart-release#33]
We see this in [aya](https://github.com/aya-rs/aya/issues/1050) where we have `aya-ebpf` and `aya-ebpf-macros`. `aya-ebpf` re-exports `aya-ebpf-macros`, but `aya-ebpf-macros` also has a *dev* dependency on `aya-ebpf` for its doctests. @dave-tucker claims this cycle makes cargo-smart-release unhappy.

Perhaps dev dependencies shouldn't be part of the algorithm? Otherwise, what is the proper way to solve this?

**Comment by Byron** [comment]
Thanks for bringing this up.

I left [a comment](https://github.com/aya-rs/aya/pull/1106/files#r1867101730), and will leave it here for posterity.

> Remove the `version = *` field and the problems will go away. `gitoxide` also does this, and also went through the trouble with the `version` field.

I think that will solve the problem.
