### ISSUE TITLE
"BUG: assure history is set here" running `cargo changelog --write` on detached head 

### ISSUE THREAD

**Issue by MingweiSamuel** [Byron/cargo-smart-release#34]
`cargo changelog --write`

simply checking out the detached head as a new branch fixed the issue

**Comment by Byron** [comment]
Thanks for reporting.

It should probably fail gracefully and with a clear message if it finds itself in a detached head state. As it's creating new commits, there should always be a reference checked out.

`cargo changelog`, however, wouldn't have such constraints even though as a fix, for now it's fine to just impose the same constraints.

**Comment by Byron** [comment]
This was fixed in https://github.com/Byron/cargo-smart-release/releases/tag/v0.21.6 .
